/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LookupRouteImport } from './routes/lookup'
import { Route as AdminShellRouteImport } from './routes/admin/_shell'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminShellIndexRouteImport } from './routes/admin/_shell/index'
import { Route as AdminShellAttendanceRouteImport } from './routes/admin/_shell/attendance'
import { Route as AdminShellLinksRouteImport } from './routes/admin/_shell/links'
import { Route as AdminShellParticipantsRouteImport } from './routes/admin/_shell/participants'
import { Route as AdminShellRoomsRouteImport } from './routes/admin/_shell/rooms'
import { Route as AdminShellSessionsRouteImport } from './routes/admin/_shell/sessions'
import { Route as AdminShellUsersRouteImport } from './routes/admin/_shell/users'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LookupRoute = LookupRouteImport.update({
  id: '/lookup',
  path: '/lookup',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminShellRoute = AdminShellRouteImport.update({
  id: '/admin/_shell',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminShellIndexRoute = AdminShellIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminShellRoute,
} as any)
const AdminShellAttendanceRoute = AdminShellAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AdminShellRoute,
} as any)
const AdminShellLinksRoute = AdminShellLinksRouteImport.update({
  id: '/links',
  path: '/links',
  getParentRoute: () => AdminShellRoute,
} as any)
const AdminShellParticipantsRoute = AdminShellParticipantsRouteImport.update({
  id: '/participants',
  path: '/participants',
  getParentRoute: () => AdminShellRoute,
} as any)
const AdminShellRoomsRoute = AdminShellRoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => AdminShellRoute,
} as any)
const AdminShellSessionsRoute = AdminShellSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => AdminShellRoute,
} as any)
const AdminShellUsersRoute = AdminShellUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminShellRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/lookup': typeof LookupRoute
  '/admin': typeof AdminShellRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/attendance': typeof AdminShellAttendanceRoute
  '/admin/links': typeof AdminShellLinksRoute
  '/admin/participants': typeof AdminShellParticipantsRoute
  '/admin/rooms': typeof AdminShellRoomsRoute
  '/admin/sessions': typeof AdminShellSessionsRoute
  '/admin/users': typeof AdminShellUsersRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/admin/': typeof AdminShellIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/lookup': typeof LookupRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/attendance': typeof AdminShellAttendanceRoute
  '/admin/links': typeof AdminShellLinksRoute
  '/admin/participants': typeof AdminShellParticipantsRoute
  '/admin/rooms': typeof AdminShellRoomsRoute
  '/admin/sessions': typeof AdminShellSessionsRoute
  '/admin/users': typeof AdminShellUsersRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/admin': typeof AdminShellIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/lookup': typeof LookupRoute
  '/admin/_shell': typeof AdminShellRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/_shell/attendance': typeof AdminShellAttendanceRoute
  '/admin/_shell/links': typeof AdminShellLinksRoute
  '/admin/_shell/participants': typeof AdminShellParticipantsRoute
  '/admin/_shell/rooms': typeof AdminShellRoomsRoute
  '/admin/_shell/sessions': typeof AdminShellSessionsRoute
  '/admin/_shell/users': typeof AdminShellUsersRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/admin/_shell/': typeof AdminShellIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/lookup'
    | '/admin'
    | '/admin/login'
    | '/admin/attendance'
    | '/admin/links'
    | '/admin/participants'
    | '/admin/rooms'
    | '/admin/sessions'
    | '/admin/users'
    | '/api/auth/$'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/lookup'
    | '/admin/login'
    | '/admin/attendance'
    | '/admin/links'
    | '/admin/participants'
    | '/admin/rooms'
    | '/admin/sessions'
    | '/admin/users'
    | '/api/auth/$'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/lookup'
    | '/admin/_shell'
    | '/admin/login'
    | '/admin/_shell/attendance'
    | '/admin/_shell/links'
    | '/admin/_shell/participants'
    | '/admin/_shell/rooms'
    | '/admin/_shell/sessions'
    | '/admin/_shell/users'
    | '/api/auth/$'
    | '/admin/_shell/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LookupRoute: typeof LookupRoute
  AdminShellRoute: typeof AdminShellRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lookup': {
      id: '/lookup'
      path: '/lookup'
      fullPath: '/lookup'
      preLoaderRoute: typeof LookupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_shell': {
      id: '/admin/_shell'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_shell/': {
      id: '/admin/_shell/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminShellIndexRouteImport
      parentRoute: typeof AdminShellRoute
    }
    '/admin/_shell/attendance': {
      id: '/admin/_shell/attendance'
      path: '/attendance'
      fullPath: '/admin/attendance'
      preLoaderRoute: typeof AdminShellAttendanceRouteImport
      parentRoute: typeof AdminShellRoute
    }
    '/admin/_shell/links': {
      id: '/admin/_shell/links'
      path: '/links'
      fullPath: '/admin/links'
      preLoaderRoute: typeof AdminShellLinksRouteImport
      parentRoute: typeof AdminShellRoute
    }
    '/admin/_shell/participants': {
      id: '/admin/_shell/participants'
      path: '/participants'
      fullPath: '/admin/participants'
      preLoaderRoute: typeof AdminShellParticipantsRouteImport
      parentRoute: typeof AdminShellRoute
    }
    '/admin/_shell/rooms': {
      id: '/admin/_shell/rooms'
      path: '/rooms'
      fullPath: '/admin/rooms'
      preLoaderRoute: typeof AdminShellRoomsRouteImport
      parentRoute: typeof AdminShellRoute
    }
    '/admin/_shell/sessions': {
      id: '/admin/_shell/sessions'
      path: '/sessions'
      fullPath: '/admin/sessions'
      preLoaderRoute: typeof AdminShellSessionsRouteImport
      parentRoute: typeof AdminShellRoute
    }
    '/admin/_shell/users': {
      id: '/admin/_shell/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminShellUsersRouteImport
      parentRoute: typeof AdminShellRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminShellRouteChildren {
  AdminShellAttendanceRoute: typeof AdminShellAttendanceRoute
  AdminShellLinksRoute: typeof AdminShellLinksRoute
  AdminShellParticipantsRoute: typeof AdminShellParticipantsRoute
  AdminShellRoomsRoute: typeof AdminShellRoomsRoute
  AdminShellSessionsRoute: typeof AdminShellSessionsRoute
  AdminShellUsersRoute: typeof AdminShellUsersRoute
  AdminShellIndexRoute: typeof AdminShellIndexRoute
}

const AdminShellRouteChildren: AdminShellRouteChildren = {
  AdminShellAttendanceRoute: AdminShellAttendanceRoute,
  AdminShellLinksRoute: AdminShellLinksRoute,
  AdminShellParticipantsRoute: AdminShellParticipantsRoute,
  AdminShellRoomsRoute: AdminShellRoomsRoute,
  AdminShellSessionsRoute: AdminShellSessionsRoute,
  AdminShellUsersRoute: AdminShellUsersRoute,
  AdminShellIndexRoute: AdminShellIndexRoute,
}

const AdminShellRouteWithChildren = AdminShellRoute._addFileChildren(
  AdminShellRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LookupRoute: LookupRoute,
  AdminShellRoute: AdminShellRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
