/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminAttendanceRouteImport } from './routes/admin/attendance'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminParticipantsRouteImport } from './routes/admin/participants'
import { Route as AdminRoomsRouteImport } from './routes/admin/rooms'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAttendanceRoute = AdminAttendanceRouteImport.update({
  id: '/admin/attendance',
  path: '/admin/attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminParticipantsRoute = AdminParticipantsRouteImport.update({
  id: '/admin/participants',
  path: '/admin/participants',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoomsRoute = AdminRoomsRouteImport.update({
  id: '/admin/rooms',
  path: '/admin/rooms',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin/attendance': typeof AdminAttendanceRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/participants': typeof AdminParticipantsRoute
  '/admin/rooms': typeof AdminRoomsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/': typeof AdminIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/attendance': typeof AdminAttendanceRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/participants': typeof AdminParticipantsRoute
  '/admin/rooms': typeof AdminRoomsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin': typeof AdminIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin/attendance': typeof AdminAttendanceRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/participants': typeof AdminParticipantsRoute
  '/admin/rooms': typeof AdminRoomsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/': typeof AdminIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin/attendance'
    | '/admin/login'
    | '/admin/participants'
    | '/admin/rooms'
    | '/admin/users'
    | '/admin/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/attendance'
    | '/admin/login'
    | '/admin/participants'
    | '/admin/rooms'
    | '/admin/users'
    | '/admin'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/admin/attendance'
    | '/admin/login'
    | '/admin/participants'
    | '/admin/rooms'
    | '/admin/users'
    | '/admin/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminAttendanceRoute: typeof AdminAttendanceRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminParticipantsRoute: typeof AdminParticipantsRoute
  AdminRoomsRoute: typeof AdminRoomsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/attendance': {
      id: '/admin/attendance'
      path: '/admin/attendance'
      fullPath: '/admin/attendance'
      preLoaderRoute: typeof AdminAttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/participants': {
      id: '/admin/participants'
      path: '/admin/participants'
      fullPath: '/admin/participants'
      preLoaderRoute: typeof AdminParticipantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/rooms': {
      id: '/admin/rooms'
      path: '/admin/rooms'
      fullPath: '/admin/rooms'
      preLoaderRoute: typeof AdminRoomsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminAttendanceRoute: AdminAttendanceRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminParticipantsRoute: AdminParticipantsRoute,
  AdminRoomsRoute: AdminRoomsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
